export const MERCHANDISES = [
  {
    id: "hX2BTPkNH",
    category: "top",
    image: "/images/BIGTshirt.jpg",
    maker: "소버먼트",
    description: "BIG 트위치 로고 티셔츠 White",
    size:"",
    quantity: 1,
    price: 22900,
  },
  {
    id: "ZQOF7gyCO",
    category: "top",
    image: "/images/CSMTshirt.jpg",
    maker: "CSM",
    description: "CSM Raglan T-SHIRT Light Grey",
    size:"",
    quantity: 1,
    price: 40700,
  },
  {
    id: "cKtHegWRX8",
    category: "top",
    image: "/images/pigment.jpg",
    maker: "디스펑트",
    description: "DREAM CATCHER PIGMENT T-SHIRT (CHARCOAL)",
    size:"",
    quantity: 1,
    price: 39000,
  },
  {
    id: "LnGmKtXS8e",
    category: "top",
    image: "/images/CLUBTshirt.jpg",
    maker: "엘리메노",
    description: "EL 스트리트 아트워크 오버핏 반팔티",
    size:"",
    quantity: 1,
    price: 21900,
  },
  {
    id: "Uts5-JkrsQ",
    category: "pants",
    image: "/images/codegraphy.jpg",
    maker: "디스펑트",
    description: "미니멀 트레이닝 essential 원턱 반바지",
    size:"",
    quantity: 1,
    price: 32000,
  },
  {
    id: "0NLkx--0as",
    category: "pants",
    image: "/images/LAFUDGE.jpg",
    maker: "트래블",
    description: "카펜터 버뮤다 스웨트 8부 팬츠 블랙",
    size:"",
    quantity: 1,
    price: 39900,
  },
  {
    id: "SYJyHUNTIY",
    category: "pants",
    image: "/images/PERSTEP.jpg",
    maker: "후브스",
    description: "딥워싱 원턱 데님 하프팬츠 다크블루",
    size:"",
    quantity: 1,
    price: 15400,
  },
  {
    id: "3nA4haKp4n",
    category: "outer",
    image: "/images/packable.jpg",
    maker: "키뮤어",
    description: "패커블 시어 후드 윈드브레이커_라이트 그레이",
    size:"",
    quantity: 1,
    price: 79000,
  },
  {
    id: "swp5mvEIfe",
    category: "outer",
    image: "/images/RELAX.jpg",
    maker: "예일",
    description: "LIGHT RELAX FIT BLOUSON IVORY",
    size:"",
    quantity: 1,
    price: 39000,
  },
];
